from .tante import TANTE
from .fno import FNO
from .tfno import TFNO
from .afno import AFNO
from .uno import UNO
from .unet_convnext import UNetConvNext
from .unet_att import AttentionUNet
from .dpot import DPOT
from .avit import AViT
from .cvit import CViT